package org.example.salamainsurance.Entity.Notification;

public enum NotificationType {
  CLAIM_CREATED,
  EXPERT_ASSIGNED,
  EXPERT_UNASSIGNED,
  REPORT_SUBMITTED,
  CLAIM_CLOSED,
  CLAIM_CANCELLED,
  REMINDER,
  FRAUD_ALERT,
  INFO_REQUEST,
  APPOINTMENT_REMINDER,
  DOCUMENT_UPLOADED,
  PAYMENT_PROCESSED,
  SYSTEM_ALERT
}
