server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/SalamaInsuranceDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pour Spring Boot 4.0.2
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Configuration Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adsalamainsurance@gmail.com
spring.mail.password=kaxy mktt athz nxzf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Optionnel : Pour activer les logs de debug (utile si ça ne marche pas)
# logging.level.org.springframework.mail=DEBUG
